Hw6
mikhailova-aa/web-technologies-2.0 pull request #5
Opened 2023-10-15 12:34 UTC by mikhailova-aa

2023-10-15 13:48 UTC, complynx requested changes

2023-10-15 13:48 UTC, complynx commented on howmuch.py
> +current_date = "2023-10-15"
Давайте лучше используем счётчик без даты в имени, но добавим ему время жизни

2023-10-15 17:21 UTC, mikhailova-aa commented
Переделала

2023-10-15 17:21 UTC, mikhailova-aa commented on howmuch.py
> +current_date = "2023-10-15"
Переделала

2023-10-16 13:08 UTC, complynx requested changes

2023-10-16 13:08 UTC, complynx commented on howmuch.py
> +redis_conn.expire(key, 24 * 3600)
Если тут делать expire, то будет "вечный" ключ, так как дедлайн будет обновляться на каждом запросе.

2023-10-16 14:10 UTC, complynx approved these changes

2023-10-16 14:12 UTC, merged